services:
  - type: web
    name: meu-site-php
    env: php
    plan: free
    branch: main
    buildCommand: composer install --prefer-dist --no-progress --no-suggest
    startCommand: vendor/bin/heroku-php-apache2
